prometheus:
  prometheusSpec:
    thanos:
      image: quay.io/thanos/thanos:v0.24.0
      version: v0.24.0
      objectStorageConfig:
        name: thanos
        key: thanos-obj-store.yaml
  service:
    type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos
  namespace: thanos
type: Opaque
data:
  thanos-obj-store.yaml: |
    type: S3
    config:
      bucket: ${bucket_name}
      endpoint: "s3.${region}.amazonaws.com"
      region: ${region}
      access_key: ${access_key}
      insecure: false
      signature_version2: false
      secret_key: ${secret_key}
      put_user_metadata: {}
      http_config:
        idle_conn_timeout: 0s
        response_header_timeout: 0s
        insecure_skip_verify: false
      trace:
        enable: false
      part_size: 0