apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.xlarge", "m5.2xlarge"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  provider:
    instanceProfile: ${INSTANCE_PROFILE}
    securityGroupSelector: 
      Name: ${CLUSTER_SG_NAME}
    subnetSelector:
        kubernetes.io/cluster/${CLUSTER_NAME}: '*'
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 50Gi
          volumeType: gp3
          iops: 3000
          encrypted: true
          kmsKeyID: ${EBS_KMS_ARN}
          deleteOnTermination: true
          throughput: 125
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 2
      httpTokens: required
    tags:
      IsTerraform: "true"
      Name: ${NAMEPREFIX}/karpenter-eks-node
      Environment: ${ENVIRONMENT}
  ttlSecondsAfterEmpty: 30
